# Generated by Django 6.0.6 on 2026-06-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_remove_invitados_id_invitado_invitados_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to='Eventos.usuarios'),
        ),
    ]
