# Generated by Django 6.0.6 on 2026-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_eventos_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='cantidad_invitados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
