# Generated by Django 6.0.6 on 2026-06-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_eventos_cantidad_invitados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lugar', models.CharField(choices=[('casa', 'Casa particular'), ('salon', 'Salón de eventos'), ('casa_eventos', 'Casa de eventos'), ('exterior', 'Exterior')], max_length=20)),
                ('hay_ninos', models.BooleanField(default=False)),
                ('hay_adultos_mayores', models.BooleanField(default=False)),
                ('vestimenta', models.CharField(choices=[('formal', 'Formal'), ('semiformal', 'Semiformal'), ('casual', 'Casual'), ('tematico', 'Temático')], max_length=20)),
                ('incluye_dj', models.BooleanField(default=False)),
                ('incluye_camarero', models.BooleanField(default=False)),
                ('incluye_decoracion', models.BooleanField(default=False)),
                ('tipo_comida', models.CharField(blank=True, max_length=100)),
                ('tipo_bebida', models.CharField(blank=True, max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='Eventos.eventos')),
            ],
            options={
                'db_table': 'cotizaciones',
            },
        ),
    ]
